# -- Project root setup --
import os as _os
from pathlib import Path as _Path
_os.chdir(_Path(__file__).resolve().parents[2])
"""
Figure 4: Topological Mixing (3 panels, 1×3)
Panel A: PCA showing extreme categories scattered within main body (7-class)
Panel B: Slope chart full-length vs region Silhouette (7-class, 3 extreme subcategories)
Panel C: Silhouette violin plot (7-class, region-replaced PCA)
Output: manuscript/figure4.png

Reproducibility:
  Panel B computes silhouette from two embedding files:
    - data/embeddings/sequence_embeddings_fulllength.pt (全长 mean pooling)
    - data/embeddings/sequence_embeddings_region_replaced.pt (extreme 用 region embedding)
  Both generated by pipeline: 07_batch_inference_final → 09_generate_region_embeddings → 10_merge
"""

import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_samples, silhouette_score

print("=" * 70)
print("Figure 4: Topological Mixing")
print("=" * 70)

plt.rcParams['figure.dpi'] = 600
plt.rcParams['savefig.dpi'] = 600
plt.rcParams['font.size'] = 8
plt.rcParams['axes.labelsize'] = 9
plt.rcParams['axes.titlesize'] = 10
plt.rcParams['xtick.labelsize'] = 8
plt.rcParams['ytick.labelsize'] = 8
plt.rcParams['legend.fontsize'] = 7
plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['font.sans-serif'] = ['DejaVu Sans']

# ── Load data ──
print("\nLoading data...")
pca_2d = np.load('data/pca/pca_embeddings_2d.npy')
pca_50d = np.load('data/pca/pca_embeddings_50d.npy')
metadata = pd.read_csv('data/metadata_final_with_en.csv')
explained_var = np.load('data/pca/explained_variance.npy')
print(f"  Sequences: {len(pca_2d)}")

# Note: current pca_50d is based on region-replaced embeddings
# (extreme categories use region embeddings, others unchanged)

# Assign 7-category labels
def assign_cat7(row):
    sub = row['subcategory']
    if sub == 'anchor': return 'Anchor'
    elif sub == 'astral95': return 'Astral95'
    elif sub == 'integrable': return 'Integrable'
    elif sub == 'random': return 'Random'
    elif sub == 'fold_switching': return 'Fold-switching'
    elif sub == 'idp': return 'IDP'
    elif sub == 'knotted': return 'Knotted'
    return 'Unknown'

metadata['cat7'] = metadata.apply(assign_cat7, axis=1)


# Colors — high contrast
COLORS_7 = {
    'Astral95': '#bdbdbd',          # gray (background structural)
    'Anchor': '#1f77b4',            # blue
    'Random': '#2ca02c',            # green
    'Integrable': '#17becf',        # cyan
    'IDP': '#9467bd',               # purple
    'Fold-switching': '#d62728',    # red
    'Knotted': '#ff7f0e',           # orange
}

# ── Compute silhouette (7-class, current PCA = region-replaced) ──
print("Computing silhouette (7-class, 50D PCA, region-replaced)...")
sil_samples = silhouette_samples(pca_50d, metadata['cat7'].values)
metadata['sil'] = sil_samples
sil_overall = silhouette_score(pca_50d, metadata['cat7'].values)
print(f"  Overall 7-class Silhouette: {sil_overall:.4f}")

for cat in ['Random', 'Integrable', 'Anchor', 'Astral95', 'Fold-switching', 'IDP', 'Knotted']:
    vals = metadata.loc[metadata['cat7'] == cat, 'sil']
    print(f"  {cat:<16s}: mean={vals.mean():+.4f}, n={len(vals)}")

# ── Compute 7-class silhouette for Panel B (from embedding files) ──
# Only IDP / Fold-switching / Knotted have region annotations.
# Slope chart shows per-subcategory silhouette change (7-class) for these three.
print("\nComputing 7-class silhouette for slope chart (3 extreme subcategories)...")
cat7_labels = metadata['cat7'].values
PCA_DIM = 50

# Full-length version
print("  Loading full-length embeddings...")
emb_fl = torch.load('data/embeddings/sequence_embeddings_fulllength.pt',
                     map_location='cpu', weights_only=True).float().numpy()
pca_fl_50d = PCA(n_components=PCA_DIM, random_state=42).fit_transform(emb_fl)
sil_fl_7class = {}
sil_fl_samples = silhouette_samples(pca_fl_50d, cat7_labels)
for cat in ['Fold-switching', 'IDP', 'Knotted']:
    mask = metadata['cat7'] == cat
    sil_fl_7class[cat] = sil_fl_samples[mask.values].mean()
print(f"  Full-length 7-class (extreme only): {sil_fl_7class}")

# Region-replaced version
print("  Loading region-replaced embeddings...")
emb_rr = torch.load('data/embeddings/sequence_embeddings_region_replaced.pt',
                     map_location='cpu', weights_only=True).float().numpy()
pca_rr_50d = PCA(n_components=PCA_DIM, random_state=42).fit_transform(emb_rr)
sil_rr_7class = {}
sil_rr_samples = silhouette_samples(pca_rr_50d, cat7_labels)
for cat in ['Fold-switching', 'IDP', 'Knotted']:
    mask = metadata['cat7'] == cat
    sil_rr_7class[cat] = sil_rr_samples[mask.values].mean()
print(f"  Region-replaced 7-class (extreme only): {sil_rr_7class}")

# Build slope data — only the 3 categories with region annotations
SLOPE_COLORS = {'Fold-switching': '#d62728', 'IDP': '#9467bd', 'Knotted': '#ff7f0e'}
slope_rows = []
SLOPE_ORDER = ['Fold-switching', 'IDP', 'Knotted']
for cat in SLOPE_ORDER:
    fl_val = sil_fl_7class[cat]
    rg_val = sil_rr_7class[cat]
    chg = ((rg_val - fl_val) / abs(fl_val) * 100) if abs(fl_val) > 1e-6 else 0
    slope_rows.append({
        'cat': cat, 'label': cat,
        'fl': fl_val, 'rg': rg_val, 'chg': chg, 'color': SLOPE_COLORS[cat]
    })
    print(f"  {cat:<16s}: {fl_val:+.3f} → {rg_val:+.3f} ({chg:+.0f}%)")

# ── Figure: 1×3 ──
fig, axes = plt.subplots(1, 3, figsize=(20, 6))

# ============ Panel A: PCA showing extreme scattered in main body ============
ax = axes[0]
non_extreme_mask = ~metadata['cat7'].isin(['Fold-switching', 'IDP', 'Knotted'])

ax.scatter(pca_2d[non_extreme_mask.values, 0], pca_2d[non_extreme_mask.values, 1],
           c='lightgray', s=1, alpha=0.3, edgecolors='none', rasterized=True)

for label in ['Fold-switching', 'IDP', 'Knotted']:
    mask = (metadata['cat7'] == label).values
    ax.scatter(pca_2d[mask, 0], pca_2d[mask, 1],
               c=COLORS_7[label], s=12, alpha=0.8, edgecolors='white', linewidths=0.3,
               zorder=5, rasterized=True)

ax.set_xlabel(f'PC1 ({explained_var[0]*100:.1f}% var)')
ax.set_ylabel(f'PC2 ({explained_var[1]*100:.1f}% var)')
ax.set_title('a', fontsize=12, fontweight='bold', loc='center', pad=10)
ax.grid(True, alpha=0.2, linewidth=0.5)

# Uniform legend (Line2D, same marker size)
legend_handles_a = [
    Line2D([0], [0], marker='o', color='w', markerfacecolor='lightgray',
           markersize=6, label='Other', linestyle='None'),
]
for label in ['Fold-switching', 'IDP', 'Knotted']:
    n = (metadata['cat7'] == label).sum()
    legend_handles_a.append(
        Line2D([0], [0], marker='o', color='w', markerfacecolor=COLORS_7[label],
               markersize=6, label=f'{label} (n={n})', linestyle='None'))
ax.legend(handles=legend_handles_a, loc='upper left', frameon=True, fontsize=7,
          framealpha=0.9, edgecolor='gray')

# Annotation: white bg, lower-left
extreme_cats = ['Fold-switching', 'IDP', 'Knotted']
extreme_sil_vals = {c: metadata.loc[metadata['cat7']==c, 'sil'].mean() for c in extreme_cats}
annot_text = '\n'.join([f'{c}: Sil = {v:.3f}' for c, v in extreme_sil_vals.items()])
annot_text += '\n(scattered within main body)'
props = dict(boxstyle='round', facecolor='white', alpha=0.9, edgecolor='gray', linewidth=0.8)
ax.text(0.02, 0.02, annot_text, transform=ax.transAxes, fontsize=6.5,
        va='bottom', ha='left', bbox=props)

# ============ Panel B: Slope chart (7-class, 3 extreme subcategories) ============
ax = axes[1]

x_left, x_right = 0.25, 0.75

# Adjust label positions to avoid overlap
def adjust_positions(values, min_gap=0.035):
    indexed = sorted(enumerate(values), key=lambda x: x[1])
    adjusted = list(values)
    for i in range(1, len(indexed)):
        idx_cur = indexed[i][0]
        idx_prev = indexed[i-1][0]
        if adjusted[idx_cur] - adjusted[idx_prev] < min_gap:
            adjusted[idx_cur] = adjusted[idx_prev] + min_gap
    return adjusted

fl_vals = [d['fl'] for d in slope_rows]
rg_vals = [d['rg'] for d in slope_rows]
fl_adj = adjust_positions(fl_vals)
rg_adj = adjust_positions(rg_vals)

for i, d in enumerate(slope_rows):
    lw = 2.5
    alpha = 0.85

    ax.plot([x_left, x_right], [d['fl'], d['rg']], color=d['color'],
            linewidth=lw, alpha=alpha)
    ax.scatter(x_left, d['fl'], color=d['color'], s=70, zorder=5,
               edgecolors='white', linewidths=0.5)
    ax.scatter(x_right, d['rg'], color=d['color'], s=70, zorder=5,
               edgecolors='white', linewidths=0.5)

    # Left value labels (4 decimal places)
    ax.text(x_left - 0.05, fl_adj[i], f'{d["fl"]:.4f}', ha='right', va='center',
            fontsize=7.5, color=d['color'])
    # Right value labels (4 decimal places)
    ax.text(x_right + 0.05, rg_adj[i], f'{d["rg"]:.4f}', ha='left', va='center',
            fontsize=7.5, color=d['color'])
    # Category name + change % below the line midpoint
    mid_y = (d['fl'] + d['rg']) / 2
    direction = '+' if d['chg'] > 0 else ''
    ax.text(0.5, mid_y - 0.012, f'{d["label"]} ({direction}{d["chg"]:.1f}%)',
            ha='center', va='top', fontsize=7.5, color=d['color'],
            fontweight='bold')

# x-axis labels already show Full-length / Region — no duplicate header needed

ax.set_xlim(0.0, 1.0)
# Auto-scale y based on data range
all_vals = [d['fl'] for d in slope_rows] + [d['rg'] for d in slope_rows]
y_min = min(all_vals) - 0.05
y_max = max(all_vals) + 0.08
ax.set_ylim(y_min, y_max)
ax.axhline(0, color='gray', linewidth=0.5, linestyle='--')
ax.set_ylabel('Silhouette Score (7-class)')
ax.set_xticks([x_left, x_right])
ax.set_xticklabels(['Full-length', 'Region'], fontsize=9)
ax.set_title('b', fontsize=12, fontweight='bold', loc='center', pad=10)
ax.grid(True, alpha=0.2, axis='y', linewidth=0.5)

# ============ Panel C: Silhouette violin plot (7-class) ============
ax = axes[2]

PLOT_ORDER_C = ['Random', 'Integrable', 'Anchor', 'Astral95', 'Fold-switching', 'IDP', 'Knotted']
violin_data = []
violin_labels = []
violin_colors = []
for cat in PLOT_ORDER_C:
    vals = metadata.loc[metadata['cat7'] == cat, 'sil'].values
    violin_data.append(vals)
    violin_labels.append(f'{cat}\n(n={len(vals)})')
    violin_colors.append(COLORS_7[cat])

positions = list(range(len(PLOT_ORDER_C)))
parts = ax.violinplot(violin_data, positions=positions,
                       showmeans=False, showmedians=False, showextrema=False)

for i, pc in enumerate(parts['bodies']):
    pc.set_facecolor(violin_colors[i])
    pc.set_alpha(0.7)

# Draw mean (black dash) and median (red solid) manually
for i in range(len(PLOT_ORDER_C)):
    vals = violin_data[i]
    mean_val = vals.mean()
    median_val = np.median(vals)
    ax.hlines(median_val, i - 0.3, i + 0.3, colors='red', linewidths=1.2, zorder=4)
    ax.hlines(mean_val, i - 0.3, i + 0.3, colors='black', linewidths=1.2,
              linestyles='dashed', zorder=4)

# Value labels ABOVE the violin (at actual max of distribution)
for i in range(len(PLOT_ORDER_C)):
    vals = violin_data[i]
    mean_val = vals.mean()
    top = vals.max()
    ax.text(i, top + 0.02, f'μ={mean_val:.3f}', ha='center', va='bottom',
            fontsize=6, fontweight='bold', color=violin_colors[i])

ax.set_xticks(positions)
ax.set_xticklabels(violin_labels, fontsize=6.5)
ax.set_ylabel('Silhouette Score')
ax.set_title('c', fontsize=12, fontweight='bold', loc='center', pad=10)
ax.axhline(0, color='gray', linewidth=0.8, linestyle='--', alpha=0.5)
ax.grid(True, alpha=0.2, axis='y', linewidth=0.5)

# Legend for mean/median
legend_handles_c = [
    Line2D([0], [0], color='black', linewidth=1.2, linestyle='dashed', label='Mean'),
    Line2D([0], [0], color='red', linewidth=1.2, linestyle='solid', label='Median'),
]
ax.legend(handles=legend_handles_c, loc='upper right', frameon=True, fontsize=7,
          framealpha=0.9, edgecolor='gray')

plt.tight_layout()
plt.savefig('manuscript/figure4.png', dpi=600, bbox_inches='tight')
plt.close()

# ============ Summary Statistics ============
print("\n" + "=" * 70)
print("FIGURE 4 — STATISTICS FOR CAPTION")
print("=" * 70)

print(f"\n{'─'*70}")
print("[Panel A] Extreme categories in PCA space (region-replaced embeddings)")
print(f"{'─'*70}")
for cat in ['Fold-switching', 'IDP', 'Knotted']:
    mask = metadata['cat7'] == cat
    n = mask.sum()
    mean_sil = metadata.loc[mask, 'sil'].mean()
    std_sil = metadata.loc[mask, 'sil'].std()
    print(f"  {cat:<16s}: n = {n:>5d}, mean Sil = {mean_sil:+.4f} ± {std_sil:.4f}")
print(f"  → All three scattered within main body, negative silhouette")

print(f"\n{'─'*70}")
print("[Panel B] Slope chart: Full-length vs Region Silhouette (7-class, 3 extreme subcategories)")
print(f"{'─'*70}")
print(f"  {'Category':<16s} {'FL Sil':>8s} {'Rg Sil':>8s} {'Change':>10s}")
print(f"  {'─'*46}")
for d in slope_rows:
    direction = '+' if d['chg'] > 0 else ''
    print(f"  {d['label']:<16s} {d['fl']:>+8.3f} {d['rg']:>+8.3f} {direction}{d['chg']:.1f}%")
print(f"  → Only IDP/Fold-switching/Knotted have region annotations")
print(f"  → Silhouette computed with 7-class labels (not collapsed to 'extreme')")
print(f"  Method: 7-class silhouette computed from embedding files")
print(f"          fulllength.pt → PCA 50D → silhouette, region_replaced.pt → PCA 50D → silhouette")

print(f"\n{'─'*70}")
print("[Panel C] Silhouette violin (7-class, region-replaced, 50D PCA)")
print(f"{'─'*70}")
print(f"  {'Category':<16s} {'n':>6s} {'Mean':>8s} {'Median':>8s} {'Std':>8s}")
print(f"  {'─'*50}")
for cat in PLOT_ORDER_C:
    vals = metadata.loc[metadata['cat7'] == cat, 'sil'].values
    print(f"  {cat:<16s} {len(vals):>6d} {vals.mean():>+8.4f} {np.median(vals):>+8.4f} {vals.std():>8.4f}")
print(f"  Overall 7-class Silhouette: {sil_overall:.4f}")

print(f"\n{'─'*70}")
print("KEY MESSAGES:")
print("  1. Extreme proteins have negative silhouette → topologically mixed")
print("  2. Region replacement effect varies by subcategory:")
for d in slope_rows:
    direction = '+' if d['chg'] > 0 else ''
    print(f"     {d['label']:<16s}: {d['fl']:+.3f} → {d['rg']:+.3f} ({direction}{d['chg']:.0f}%)")
print("  3. Only Random has strong positive silhouette (grammar violation)")
print("  4. Knotted most negative → knot topology invisible to ESM-2")
print(f"{'─'*70}")

print(f"\nSaved: manuscript/figure4.png")
print("=" * 70)
